### PR TITLE
fix(formatter): json needs a distinct tool entry

### PR DESCRIPTION
**Pull request by IamXander**
This fixes https://github.com/aspect-build/rules_lint/issues/121 in a similar way to how this sort of thing was fixed in https://github.com/aspect-build/rules_lint/pull/99
---

### Type of change

- Bug fix (change which fixes an issue)

### Test plan

- Manual testing; please provide instructions so we can reproduce:
Verified that with JSON is now being formatting using my fork and branch!

### CODE REVIEW

**Comment by alexeagle** [comment]
Thanks, it's extra embarrassing since I had that bug in mind when I did the refactor to make json its own language, but convinced myself it was working. Obviously this needs a new test fixture that checks formatting works one language at a time.

**Comment by IamXander** [comment]
Any objection to merging this while you work on the test harness framework? I'll add a test based on how you want to structure the unit testing.

**Comment by IamXander** [comment]
Ah I see I made a mistake! Ran `format` so it should pass now

**Comment by alexeagle** [comment]
Making it a separate tool is one way to resolve this, but the simpler way is to copy from CSS and HTML handling. I added coverage for it to #126 which I think resolves #121 in place of this PR, wdyt?

**Comment by IamXander** [comment]
Happy to close this in favor of https://github.com/aspect-build/rules_lint/pull/126. Ngl makes me a little sad that my name is not making it into the repo ;). However, its totally fine. Just happy to see it fixed.

**Comment by alexeagle** [comment]
I have no doubt we'll have more of your commits in the history! :)

**Pull request closed without merging**
